steps:
- name: 'cd'
  args: ['SupportForce/']
# Build
- name: 'gcr.io/support-force/ng'
  args: ['build']
# Upload to Bucket
- name: 'gcr.io/support-force/gsutil'
  args: ['-m', 'cp', '-r', './dist', 'gs://support-force']